apiVersion: apps/v1
kind: Deployment
metadata:
  name: load-generator-deployment
  namespace: test-app
  labels:
    app: load-generator
spec:
  replicas: 20
  selector:
    matchLabels:
      app: load-generator
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 50% 
      maxSurge: 50%
  template:
    metadata:
      labels:
        app: load-generator
    spec:
      containers:
      - name: python-loader
        image: ttl.sh/my-guestbook-loader:5e48d5f
        imagePullPolicy: Always
      restartPolicy: Always